name: run-github-stats-checkpoint

on:
  workflow_dispatch:
  schedule:
  #   # Daily at 10:00 IST
    - cron: "30 4 * * 3"
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    paths:
      - 'tests/data_validation/great_expectations/**'
